config/routes.rb
Rails.application.routes.draw do
  resources :arts

  root 'arts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  validates :colors, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  def index
    @arts = Art.all.order(created_at: :desc)
  end

  def show
    @art = Art.find(params[:id])
  end

  def new
    @art = Art.new
  end

  def create
    colors = []
    params[:colors].values.each do |row|
      colors << row.values
    end
    @art = Art.new(colors: colors)
    if @art.save
      redirect_to art_path(@art)
    else
      redirect_to new_art_path(@art)
    end
  end

  def edit
  end

  def update
    colors = []
    params[:colors].values.each do |row|
      colors << row.values
    end
    if @art.update(colors: colors)
      redirect_to art_path(@art)
    else
      redirect_to edit_art_path(@art)
    end

  end

  def destroy
  end

  private

    def set_art
      @art = Art.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/art_helper.rb
module ArtHelper
end

app/views/arts/_art.html.erb
<div class="art">
  <% art.colors.each do |row| %>
    <div class="art__row">
      <% row.each do |pixel| %>
        <div class="art__pixel" style="background:<%= pixel %>">
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/arts/edit.html.erb
<% content_for :wrapper_class, 'wrapper__centered' %>

<%= simple_form_for @art, html: {class: "art-form"} do |f| %>
  <div class="art-form__top">
    <% 8.times.each do |i| %>
    <div class="art-form__row">
      <% 8.times.each do |ii| %>
      <input class="art-form__input" maxlength="7" placeholder="#ffffff" value="<%= @art.colors[i][ii] unless @art.colors[i].blank? %>" name="colors[<%= i %>][<%= ii %>]">
      <% end %>
    </div>
    <% end %>
  </div>
  <div class="art-form__bottom">
    <%= f.submit 'Save', class: "button button--primary" %>
  </div>
<% end %>

app/views/arts/index.html.erb
<div class="art-list">
  <% @arts.each do |art| %>
    <%= link_to art do %>
      <%= render art %>
    <% end %>
  <% end %>
</div>

app/views/arts/new.html.erb
<% content_for :wrapper_class, 'wrapper__centered' %>

<%= simple_form_for @art, html: {class: "art-form"} do |f| %>
  <div class="art-form__top">
    <% 8.times.each do |i| %>
    <div class="art-form__row">
      <% 8.times.each do |ii| %>
      <input class="art-form__input" maxlength="7" placeholder="#ffffff" name="colors[<%= i %>][<%= ii %>]">
      <% end %>
    </div>
    <% end %>
  </div>
  <div class="art-form__bottom">
    <%= f.submit 'Save', class: "button button--primary" %>
  </div>
<% end %>

app/views/arts/show.html.erb
<% content_for :wrapper_class, 'wrapper__centered' %>

<%= render @art %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pixel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav">
      <div class="nav__left">
        <%= link_to "PIXEL", arts_path, class: "nav__link" %>
      </div>
      <div class="nav__right">
        <%= link_to "Create Art", new_art_path, class: "nav__link" %>
      </div>
    </nav>
    <div class="wrapper <%= content_for :wrapper_class %>">
      <%= yield %>
    </div>
  </body>
</html>